# Generated by Django 6.0.1 on 2026-04-12 21:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('BOOKING', 'Booking'), ('SOCIAL', 'Social'), ('ACCOUNT', 'Account'), ('STAFF', 'Staff'), ('ANNOUNCEMENT', 'Announcement'), ('WARNING', 'Warning'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
