# Generated by Django 6.0.1 on 2026-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unread_notifs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
