# Generated by Django 6.0.1 on 2026-04-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_unread_notifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, null=True),
        ),
    ]
