# Generated by Django 6.0.1 on 2026-05-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('SOCIAL', 'Social'), ('STAFF', 'Staff'), ('ANNOUNCEMENT', 'Announcement'), ('WARNING', 'Warning'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
    ]
