# Generated by Django 6.0.1 on 2026-01-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
