# Generated by Django 6.0.1 on 2026-02-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_session_max_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('COMPETITIVE', 'Competitive')], default=('CASUAL', 'Casual'), max_length=15),
        ),
        migrations.AddField(
            model_name='court',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='court',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('court', 'start_time'), name='unique_court_start'),
        ),
    ]
